language: php

sudo: true

php:
  - 7.2

env:
  global:
    - MODULE_NAME='oeaw'
    - DRUPAL_REPO='http://git.drupal.org/project/drupal.git'
    - DRUPAL_VERSION='8.6.*'
    - PHPCS_VERSION='2.*'
    - CODER_VERSION='8.*'



# Cache Composer & Drush directories.
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini

  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  # - composer self-update

  # Drush.
  - composer global require drush/drush:~8.1

  # Codesniffer.
  - composer global require squizlabs/php_codesniffer:$PHPCS_VERSION
  
  - composer global require phpunit/phpunit ^6.5
  - composer global require acdh-oeaw/repo-php-util
  
  # Coder.
  - composer global require drupal/coder:$CODER_VERSION
  - ln -s ~/.composer/vendor/drupal/coder/coder_sniffer/Drupal ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/

  - composer global update
  
  # Ensure the PHP environment is ready.
  - phpenv rehash
  
install:
  - git clone $DRUPAL_REPO
  - cd drupal && composer install && cd -
  - mkdir -p drupal/modules/$MODULE_NAME
  # switched to doing it this way because it makes local testing a bit easier.
  # create symbolic links to all of the files/folders in the module directory
  - for d in $(pwd)/*; do ln -s "$d" "drupal/modules/$MODULE_NAME"; done

  # remove the recursive drupal folder from the symlinks
  - rm -f drupal/modules/$MODULE_NAME/drupal

  - cd drupal

before_script:

  # This fixes a fail when install Drupal.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Mysql might time out for long tests, increase the wait timeout.
  - mysql -e 'SET @@GLOBAL.wait_timeout=1200'

  # Install Drupal and enable the required modules (including this one).
  - mysql -e 'create database drupal;'  
  - cd $TRAVIS_BUILD_DIR/drupal && drush --yes site-install standard --db-url="mysql://root@127.0.0.1/drupal"

  # Dependency Modules
  #- cp -pr $TRAVIS_BUILD_DIR/* $TRAVIS_BUILD_DIR/drupal/modules/oeaw
  - cd $TRAVIS_BUILD_DIR/drupal && drush --yes en $MODULE_NAME
  - cd $TRAVIS_BUILD_DIR/drupal && drush --yes en simpletest

  # Export web server URL for browser tests.
  - export SIMPLETEST_BASE_URL=http://localhost:8080

  # Export database variable for kernel tests.
  - export SIMPLETEST_DB=mysql://root:@127.0.0.1/drupal
  
  # Start a web server.
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done
  - mkdir -p $TRAVIS_BUILD_DIR/drupal/modules/$MODULE_NAME_diff
   

script:

  - composer run-script drupal-phpunit-upgrade
  
  #- phpcs --report=full --standard=Drupal --warning-severity=0 $TRAVIS_BUILD_DIR/drupal/modules/$MODULE_NAME --ignore=bin,*.css,gulpfile.js,libraries,modules/contrib,vendor
  # Run code sniffer.
  # Warnings are disabled until the SMS notifier is ported.
  #- 

  # Drupal "SimpleTests" via run-tests.sh
  #- cd $TRAVIS_BUILD_DIR/drupal
  #- php core/scripts/run-tests.sh --verbose --color --module $MODULE_NAME --php $(which php) --url http://127.0.0.1:8080

  # PHP Unit Tests  
  - $HOME/.composer/vendor/bin/phpunit -c core/phpunit.xml.dist modules/oeaw/tests/src/Unit/Model/OeawResourceChildrenTest.php
  - $HOME/.composer/vendor/bin/phpunit -c core/phpunit.xml.dist modules/oeaw/tests/src/Unit/Model/OeawResourceCustomDataTest.php
  - $HOME/.composer/vendor/bin/phpunit -c core/phpunit.xml.dist modules/oeaw/tests/src/Unit/Model/OeawResourceTest.php
  #- $HOME/.composer/vendor/bin/phpunit -c core/phpunit.xml.dist modules/oeaw/tests/src/Unit/OeawFunctionsTest.php

  - phpcs --report=full --standard=PSR2 --warning-severity=0 $TRAVIS_BUILD_DIR/drupal/modules/oeaw
  #- phpcs --report=diff=$TRAVIS_BUILD_DIR/drupal/modules/$MODULE_NAME_diff --standard=Drupal $TRAVIS_BUILD_DIR/drupal/modules/oeaw/src/

after_success:
  - phpcbf --patch --standard=PSR2 $TRAVIS_BUILD_DIR/drupal/modules/oeaw/src/ 
  #- patch -p0 -ui $TRAVIS_BUILD_DIR/drupal/modules/$MODULE_NAME_diff/oeaw/src/

deploy:
    provider: pages
    skip-cleanup: true
    local-dir: $TRAVIS_BUILD_DIR/drupal/modules/oeaw/
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
        branch: master
        
        
